[{"Owner":"fczuardi","Date":"2017-01-16T15:23:46Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tI don_t_t know if this is the proper place to report bugs_co_ but I couldnt find the Issues link of this project github page.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tI am trying to use babylon as a browserify module with the budo webserver_dd_ _lt_a href_eq__qt_https_dd_//github.com/mattdesl/budo_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//github.com/mattdesl/budo_lt_/a_gt_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tHere is my index.js_dd_\n_lt_/p_gt_\n\n_lt_pre class_eq__qt_ipsCode_qt__gt_\n\tvar BABYLON _eq_ require(_t_babylonjs/babylon.max_t_)_sm_\nvar html _eq_ require(_t_bel_t_)_sm_\nvar canvas _eq_ html`&lt_sm_canvas id_eq__qt_renderCanvas_qt_&gt_sm_&lt_sm_/canvas&gt_sm_`_sm_\ndocument.body.appendChild(canvas)_sm_\n\twindow.addEventListener(_t_DOMContentLoaded_t__co_ function() {\n    console.log(_t_DOMContentLoaded_t_)_sm_\n    console.log(canvas)_sm_\n    var engine _eq_  new BABYLON.Scene(canvas_co_ true)_sm_\n})_sm_\n\t_lt_/pre_gt_\n\n_lt_p_gt_\n\tThen_co_ when I open localhost_dd_9966 I get the error of the title_dd_\n_lt_/p_gt_\n\n_lt_p_gt_\n\t_qt_Uncaught TypeError_dd_ Cannot read property _t_push_t_ of undefined_qt_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tThe line that throws this error is the line 16958 of babylon.max.js which might be coming from _lt_a href_eq__qt_https_dd_//github.com/BabylonJS/Babylon.js/blob/49bde9f67194ecc773c07a4ee0064fe836914b59/src/babylon.scene.ts#L575_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//github.com/BabylonJS/Babylon.js/blob/49bde9f67194ecc773c07a4ee0064fe836914b59/src/babylon.scene.ts#L575_lt_/a_gt_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tAny ideas of what I could be doing wrong?\n_lt_/p_gt_\n\n_lt_p_gt_\n\tThanks!\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"Sebavan","Date":"2017-01-17T00:33:59Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tHello_co_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tI guess you forgot the creation of the engine and are creating the scene directly which tries to add itself to the engine on the line you shared but as the engine is replaced by a canvas in your case_co_ the property scenes does not exist and ends up in the exception you see. try the following instead_dd_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tvar engine _eq_ new BABYLON.Engine(canvas_co_ true)_sm_\n_lt_/p_gt_\n\n_lt_p_gt_\n\t var scene _eq_ new BABYLON.Scene(engine)_sm_\n_lt_/p_gt_\n\n_lt_p_gt_\n\t \n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"fczuardi","Date":"2017-01-18T17:04:09Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t_lt_p_gt_\n\tThanks! I got it wowrking_co_ messed up the Engine bit indeed.\n_lt_/p_gt_\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"}]