[{"Owner":"will233","Date":"2015-03-14T19:54:10Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_I tried to UV map the default scene cube_co_ and apply a texture. I added a texture to the default material of the cube(I think) by following this tut _lt_a href_eq__qt_http_dd_//blogs.msdn.com/b/eternalcoding/archive/2013/06/28/babylon-js-how-to-load-a-babylon-file-produced-with-blender.aspx_qt_ rel_eq__qt_external nofollow_qt__gt_http_dd_//blogs.msdn.com/b/eternalcoding/archive/2013/06/28/babylon-js-how-to-load-a-babylon-file-produced-with-blender.aspx_lt_/a_gt_. When i export I get this log_dd_ _lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_    Babylon.js Exporter version_dd_ 1.7.0_co_ Blender version_dd_ 2.72 (sub 0)_lt_br_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ Conversion from Blender to Babylon.js _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_br_gt_    Python World class constructor completed_lt_br_gt_    processing begun of material_dd_  cube.Material_lt_br_gt_    Diffuse texture found_lt_br_gt__lt_span style_eq__qt_color_dd_#ff0000_sm__qt__gt_Error encountered processing image file_dd_  C_dd_\\Users\\me\\Documents\\blends\\ground.png_co_ Error_dd_  _t_C_dd_\\\\Users\\\\me\\\\Documents\\\\blends\\\\ground.png_t_ and _t_C_dd_\\\\Users\\\\me\\\\Documents\\\\blends\\\\ground.png_t_ are the same file_lt_/span_gt__lt_br_gt_    WARNING image texture type not recognized_dd_  &lt_sm_bpy_struct_co_ MaterialTextureSlot(_qt_Tex_qt_)&gt_sm__co_ ignored._lt_br_gt_    processing begun of mesh_dd_  Cube_lt_br_gt_        num positions      _dd_  30_lt_br_gt_        num normals        _dd_  30_lt_br_gt_        num uvs            _dd_  60_lt_br_gt_        num uvs2           _dd_  0_lt_br_gt_        num colors         _dd_  0_lt_br_gt_        num indices        _dd_  36_lt_br_gt_    processing begun of camera (FreeCamera)_dd_  Camera_lt_br_gt_    processing begun of light (POINT)_dd_  Lamp_lt_br_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ Writing of scene file started _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_br_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ Writing of scene file completed _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_br_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ end of processing _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_Thank you for any help._lt_br_gt_ _lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"will233","Date":"2015-03-16T09:57:23Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_Is the blender exporter currently broken? I tried this with different versions of blender. I tried it in Ubuntu. I tried it with downloaded blends. I always get same error. Is it possible to get an older version of the exporter?_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"JCPalmer","Date":"2015-03-16T13:51:48Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_Looking at this now.  If I do anything on weekends_co_ it is solely my own stuff.  For search purposes_co_ GIT (and every other source code management system) always allows you to get previous versions.  Assuming you are using the Github interface_co_ display the history file in question.  Select your version_co_ click on raw.  Select everything_co_ Crtl-A_co_ and put on clipboard.  Paste it into a local file &amp_sm_ save._lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_Hold off on that for a while.  Another thing for searchers is_dd_  the exporter tries to copy the image file so a version will also reside in the same directory as the created .babylon.  Blender_co_ I think_co_ can also encapsulate a texture file inside of a .blend_co_ so this gets an external version back in that case._lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_I am glad you posted your log file.  From it I see you have uvs.  The real problem line is the one after the error you highlighted.  The copy fail is understandable_co_ since you are creating the .babylon in the same dir as the texture._lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_stay tuned._lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"JCPalmer","Date":"2015-03-16T14:48:26Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_@will233 -  Good news.  Think you can go forward assuming it is working.  Thanks for bring attention to this._lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_@Deltakosh - The image type not recognized warning was put in by m0ppers_co_ never communicated with him_co_ in _lt_a href_eq__qt_https_dd_//github.com/BabylonJS/Babylon.js/commit/a7e8e39e965dcca597d321d7057eaeee4686af09_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//github.com/BabylonJS/Babylon.js/commit/a7e8e39e965dcca597d321d7057eaeee4686af09_lt_/a_gt__lt_/p_gt__lt_p_gt_ _lt_/p_gt__lt_p_gt_Before_co_ there was no warning there.  It is because only at the end are things elif_t_d that this warning shows erroneously for diffuse textures.  Can a given texture in a single iteration of this loop be multiple types?  If so_co_ should probably just delete this warning_co_ unless we want to add a boolean_co_ useFound_co_ and only show warning if !useFound._lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"Deltakosh","Date":"2015-03-16T20:25:01Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_Clearly agree. I_t_ll fix that_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"will233","Date":"2015-03-16T23:49:32Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_For my part that was pretty stupid. I apologize. I updated and now everything works great. Thanks a lot guys._lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"}]