[{"Owner":"Lightnet","Date":"2016-11-26T19:54:16Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t_lt_p_gt_\n\tEvery time I get zero error on the console log and it pain to find the error. When I was debug on chrome I find nothing and scene disappear. Only to notice that babylon hide the errors that I need to find which lines  give. Is there way to get the debug log show?\n_lt_/p_gt_\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"RaananW","Date":"2016-11-28T08:53:18Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tHi_co_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tBabylon only _qt_hides_qt_ the errors when the user has the option to define an onError callback. if no onError callback is defined_co_ the error will be _qt_ignored_qt_.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tWhen loading a scene for example_co_ babylon wraps the entire loading process in a try - catch  - _lt_a href_eq__qt_https_dd_//github.com/BabylonJS/Babylon.js/blob/master/src/Loading/babylon.sceneLoader.ts#L198_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//github.com/BabylonJS/Babylon.js/blob/master/src/Loading/babylon.sceneLoader.ts#L198_lt_/a_gt_ . Notice that if no onerror defined_co_ nothing will really happen. Babylon will fail silently. You can either turn on chrome_t_s _qt_pause on exceptions_qt__co_ and tick the _qt_pause on caught exceptions_qt__co_ which will be a lot of fun_co_ OR set the onerror function when calling the load function.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tHope this helps (and I do hope it actually correlates to your problem).\n_lt_/p_gt_\n\n_lt_p_gt_\n\t \n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"}]