[{"Owner":"styxxx","Date":"2015-10-26T19:39:50Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_div_gt_Hi_co__lt_/div_gt__lt_div_gt_ _lt_/div_gt__lt_div_gt_I tried to make a simple object (sphere with some texture) but exporting suddenly fails after I changed some textures with the message_dd__lt_br_gt__lt_em_gt_ERROR_dd_  Converting py args to operator properties_dd_ _dd_ keyword _qt_use_aspect_qt_ unrecognized_lt_/em_gt__lt_/div_gt__lt_div_gt__lt_br_gt_See the copy of the log file below._lt_/div_gt__lt_div_gt_No .babylon file is created._lt_/div_gt__lt_div_gt_ _lt_/div_gt__lt_div_gt_ _lt_/div_gt__lt_div_gt_ _lt_/div_gt__lt_div_gt_Exporter version_dd_ 3.0.6_co_ Blender version_dd_ 2.72 (sub 0)_lt_/div_gt__lt_div_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ Conversion from Blender to Babylon.js _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_/div_gt__lt_div_gt_Python World class constructor completed_lt_/div_gt__lt_div_gt_processing begun of mesh_dd_  Sphere_lt_/div_gt__lt_div_gt_processing begun of baked material_dd_  Sphere_lt_/div_gt__lt_div_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ An error was encountered _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_/div_gt__lt_div_gt_  File _qt_/home/styxxx/.config/blender/2.72/scripts/addons/io_export_babylon.py_qt__co_ line 288_co_ in execute_lt_/div_gt__lt_div_gt_    mesh _eq_ Mesh(object_co_ scene_co_ nextStartFace_co_ forcedParent_co_ nameID_co_ self)_lt_/div_gt__lt_div_gt_  File _qt_/home/styxxx/.config/blender/2.72/scripts/addons/io_export_babylon.py_qt__co_ line 694_co_ in __init___lt_/div_gt__lt_div_gt_    bakedMat _eq_ BakedMaterial(exporter_co_ object_co_ recipe)_lt_/div_gt__lt_div_gt_  File _qt_/home/styxxx/.config/blender/2.72/scripts/addons/io_export_babylon.py_qt__co_ line 1871_co_ in __init___lt_/div_gt__lt_div_gt_    bpy.ops.uv.smart_project(angle_limit _eq_ 66.0_co_ island_margin _eq_ 0.0_co_ user_area_weight _eq_ 1.0_co_ use_aspect _eq_ True)_lt_/div_gt__lt_div_gt_  File _qt_/usr/share/blender/scripts/modules/bpy/ops.py_qt__co_ line 188_co_ in __call___lt_/div_gt__lt_div_gt_    ret _eq_ op_call(self.idname_py()_co_ None_co_ kw)_lt_/div_gt__lt_div_gt_ERROR_dd_  Converting py args to operator properties_dd_ _dd_ keyword _qt_use_aspect_qt_ unrecognized_lt_/div_gt__lt_div_gt__eq__eq__eq__eq__eq__eq__eq__eq__eq_ end of processing _eq__eq__eq__eq__eq__eq__eq__eq__eq__lt_/div_gt__lt_div_gt_elapsed time_dd_  0 min_co_ 0.0243 secs_lt_/div_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"JCPalmer","Date":"2015-10-26T23:45:42Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_Blender 2.72 is no longer supported.  It still works when exporter is not required to bake materials_co_ but too old otherwise.  Change to 2.75_co_ if still available._lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"}]