[{"Owner":"dbhvk","Date":"2018-10-03T13:03:20Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tI_t_m trying to load the following GLTF (https_dd_//github.com/BabylonJS/Babylon.js/blob/master/src/Tools/babylon.filesInput.ts#L161) in a sandbox-like manner but without using the drop monitor or an standard file input.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tI do have the file instance for each file_co_ and when I manually set the lowercased-name of the file + the file instance on the FilesToLoad object_co_ the GLTF will fail to load with the following error_dd_\n_lt_/p_gt_\n\n_lt_pre_gt_\n_lt_code_gt_nÂ {cameras_dd_ Array(0)_co_ lights_dd_ Array(0)_co_ meshes_dd_ Array(2)_co_ skeletons_dd_ Array(0)_co_ particleSystems_dd_ Array(0)_co_Â â€¦} _qt_Unable to load from blob_dd_http_dd_//localhost_dd_3000/2a140a19-0e8d-47a6-bad0-d4d8b2e0c1c7_dd_ #/bufferViews/6_dd_ Invalid typed array length_dd_ 288_qt_ Error_dd_ #/bufferViews/6_dd_ Invalid typed array length_dd_ 288\n    at preview.js_dd_36\npreview.js_dd_36 Uncaught (in promise) Error_dd_ #/bufferViews/6_dd_ Invalid typed array length_dd_ 288\n    at preview.js_dd_36\n[...]\nbundle.js_dd_162382 BJS - [09_dd_58_dd_31]_dd_ Error while trying to load image_dd_ [object Blob]_lt_/code_gt__lt_/pre_gt_\n\n_lt_p_gt_\n\tI_t_ve been trying to load GLTFs and GLBs with texture dependencies (with no luck). The error while loading a blob is common as well. Any ideas on where to start to debug this?\n_lt_/p_gt_\n\n_lt_p_gt_\n\tThe scene is loading with the standard scene loader pointing to an object url with the file extension correctly forced. It works for any gltf/glb with bundled base64 materials.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tUpdate (relevant gltf parts)_dd_\n_lt_/p_gt_\n\n_lt_pre_gt_\n_lt_code_gt_      {\n         _qt_bufferView_qt_ _dd_ 6_co_\n         _qt_byteOffset_qt_ _dd_ 0_co_\n         _qt_componentType_qt_ _dd_ 5126_co_\n         _qt_count_qt_ _dd_ 36_co_\n         _qt_max_qt_ _dd_ [\n            1.000000_co_\n            1.000000\n         ]_co_\n         _qt_min_qt_ _dd_ [\n            -1.000000_co_\n            -1.000000\n         ]_co_\n         _qt_type_qt_ _dd_ _qt_VEC2_qt_\n      }\n\n[...]\n\n      {\n         _qt_buffer_qt_ _dd_ 0_co_\n         _qt_byteLength_qt_ _dd_ 288_co_\n         _qt_byteOffset_qt_ _dd_ 1572_co_\n         _qt_target_qt_ _dd_ 34962\n      }_lt_/code_gt__lt_/pre_gt_\n\n_lt_p_gt_\n\t_lt_br /_gt_\n\tÂ \n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"Sebavan","Date":"2018-10-03T16:21:44Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tThis error is usually raised by an invalid Glb/tf file. You could try to validate your file in the Khronos gltf validation tool or through the babylonjs inspector in the gltf file.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tÂ \n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-03T16:22:40Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tOh it loads just fine in the sandbox + it_t_s a model from _lt_span style_eq__qt_background-color_dd_#ffffff_sm_color_dd_#353c41_sm_font-size_dd_14px_sm__qt__gt_Khronos_lt_/span_gt__lt_span style_eq__qt_background-color_dd_#ffffff_sm_color_dd_#353c41_sm_font-size_dd_14px_sm__qt__gt_ï»¿_lt_/span_gt__t_ own example repoÂ \n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"Sebavan","Date":"2018-10-03T16:37:24Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tOh that is more interesting then_co_ could you try recreating the issue in the playground ?\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-04T20:46:21Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tHmm_co_ works in the playground_co_ but ported it to codepen so I can initialize stuff myself and get a different error (but still an error)_co_ can you check please?_lt_br /_gt_\n\t_lt_a href_eq__qt_https_dd_//codepen.io/belohlavek/pen/ZqOWWW_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//codepen.io/belohlavek/pen/ZqOWWW_lt_/a_gt_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tThe error should be_dd_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tbabylon.js_dd_1 Uncaught (in promise) Error_dd_ #/images/1/uri_dd_ Failed to load _t_AnimatedCube_MetallicRoughness.png_t__dd_ 404Â _lt_br /_gt_\n\t_lt_br /_gt_\n\tI_t_m fine with that one (that_t_s what I get on the Playground btw)_co_ means that I need to add more files to the FilesToLoad list.\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"bghgary","Date":"2018-10-04T22:19:32Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tIf you want to use _qt_file_dd__qt_ to load files_co_ all the files that are referenced by the glTF must be included in the files. In this case_co_ the glTF is inlined_co_ but the images that it references are not present in the list.\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-05T00:12:34Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tYep_co_ the thing is that_t_s not the error I get on codepen.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tIf you run the code on the playground_co_ the error will inform that images cannot be found_co_ that_t_s fine.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tFor codepen and my codebase I get two different errors for the same babylon version. So just to clarify_dd_\n_lt_/p_gt_\n\n_lt_p_gt_\n\tBJS - [21_dd_11_dd_46]_dd_ Unable to load from file_dd_simon_scene.gltf_dd_ loadAssets of unknown\n_lt_/p_gt_\n\n_lt_p_gt_\n\t_lt_span class_eq__qt_ipsEmoji_qt__gt_ðŸ‘†_lt_/span_gt_that_t_s the codepen error and it_t_s not the expected one\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"bghgary","Date":"2018-10-05T00:44:18Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tI_t_m not getting the error you are getting for the codepen link you sent.\n_lt_/p_gt_\n\n_lt_p_gt_\n\tThere are a couple of issues with the codepen page_dd_\n_lt_/p_gt_\n\n_lt_ol_gt_\n\t_lt_li_gt_\n\t\tIn order to load glTF files_co_ you need to include loaders/babylon.glTFFileLoader.js (for example from here_dd_Â _lt_a href_eq__qt_https_dd_//cdn.babylonjs.com/loaders/babylon.glTFFileLoader.js_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//cdn.babylonjs.com/loaders/babylon.glTFFileLoader.js)_lt_/a_gt_ see _lt_a href_eq__qt_http_dd_//doc.babylonjs.com/how_to/gltf#setup_qt_ rel_eq__qt_external nofollow_qt__gt_http_dd_//doc.babylonjs.com/how_to/gltf#setup_lt_/a_gt_\n\t_lt_/li_gt_\n\t_lt_li_gt_\n\t\tCodepen appears to stop execution when any exception is thrown. There is an exception that is being thrown by Babylon because it is trying to check if there is a manifest. You can disable this by calling _qt_engine.enableOfflineSupport _eq_ false_qt_ after creating the engine.\n\t_lt_/li_gt_\n_lt_/ol_gt_\n\n_lt_p_gt_\n\tAfter fixing these two_co_ I get the reference errors for the external files.\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-05T13:01:06Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tYou are right_co_ that generates the expected errors on codepen!_lt_br /_gt_\n\t_lt_br /_gt_\n\tThere_t_s still my inicial issue that I can_t_t replicate elsewhere_co_ so I_t_ll beat my head against the wall a bit during the weekend a report back if I can reproduce it\n_lt_/p_gt_\n\n_lt_p_gt_\n\tCheers\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-05T15:52:42Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tA gltf file would reference a texture like_dd_ Texture.png_lt_br /_gt_\n\tBut that name doesn_t_t contain the _qt_file_dd__qt_ prefix_co_ how does babylon look inside the FilesToLoad in the first place? Where is the _qt_file_dd__qt_ added?\n_lt_/p_gt_\n\n_lt_p_gt_\n\tLooking at_dd__lt_br /_gt_\n\t_lt_a href_eq__qt_https_dd_//github.com/BabylonJS/Babylon.js/blob/1d2dea433c7ea5db14fefa1ea9acceb756a3db10/src/Tools/babylon.tools.ts#L857-L861_qt_ rel_eq__qt_external nofollow_qt__gt_https_dd_//github.com/BabylonJS/Babylon.js/blob/1d2dea433c7ea5db14fefa1ea9acceb756a3db10/src/Tools/babylon.tools.ts#L857-L861_lt_/a_gt_\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"bghgary","Date":"2018-10-05T16:40:11Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tAh_co_ yes. That_t_s a good observation. You need to put _qt_file_dd__qt_ as the first parameter rootUrl instead of putting it as part of the second parameter sceneFilename. The rootUrl will be prepended to the uris of the glTF file.\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"},{"Owner":"dbhvk","Date":"2018-10-05T17:29:01Z","Content":"_lt_div class_eq__qt_mages_qt__gt_\n\t\t\t\n_lt_p_gt_\n\tThat was it_co_ rock and roll!\n_lt_/p_gt_\n\n_lt_p_gt_\n\tFor some reason the error reports where super obscure on my project_co_ but at the end of the day the issues were the same.\n_lt_/p_gt_\n\n\n\t\t\t\n\t\t_lt_/div_gt_\n\n\t\t_lt_div class_eq__qt_ipsI_qt__gt__lt_/div_gt__lt_/div_gt_"}]